### ISSUE TITLE
Add Google Search console site verification

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ecosystem-documentation#19]
We need to enable google search console for the site in order to be able to query for incoming broken URLs.

This does *not* require activating google analytics. It can be done with static ownerhsip verification via header tags.

**Comment by oraNod** [comment]
@ssbarnea Is the google search console publicly available?

**Comment by ssbarnea** [comment]
@oraNod Yes and no. Is free but people cannot randomly query stuff about sites they do not own. Imagine that you don't want some "other" company to look into the search queries made on your competitor.

Please, do not confuse this with Google Analytics and tracking, this is NOT ADDING ANY TRACKING CODE!

**Comment by samccann** [comment]
Can you add in this issue how you created the details that are in the PR? In case it ends up other projects want to do this as well, we'll have the full details in this issue.

**Comment by oraNod** [comment]
I've discussed this with @ssbarnea and will add some details here for the record.

The Google Search console visualizes anonymous data related to site traffic that comes from Google Search. The data does not track users in any way or provide any sort of analytics beyond things like search terms and pages with the most views. The data is also useful for identifying broken urls that result in 404.

To access the Google Search console, you need an email address that is connected with a Google account. Given that the console gives you insights into Google Search specifically that should not be a surprise. Nor should it be of concern. It would be more concerning if that data was publicly available.

The meta tag that Sorin's PR adds to the site simply enables access to that data by verifying ownership. You can read more about that here: https://support.google.com/webmasters/answer/9008080?visit_id=638380912474619163-3663793982&rd=1#meta_tag_verification&zippy=%2Chtml-tag

**Comment by oraNod** [comment]
@samccann I've added a comment next to the `meta` tag in Sorin's PR to explain why the site verification is there. After looking through the details some more I really can't see any reason not to proceed with this. It might be worth documenting somewhere how folks can request access to the Google Search console, which is more or less just asking one of the repository admins (right now that is the Ansible community team at Red Hat, Sorin, and Adam Miller).

It is also probably a good idea to make sure that we document this as something that relates to whatever project docs are at the top-level Ansible namespace in Read The Docs. For example if the ecosystem-documentation repository someday gets delegated to a subproject the site verification will no longer work.

**Comment by samccann** [comment]
sounds good. thanks for digging into the details and explaining it all!
