### ISSUE TITLE
Avoid using .html extension for pages

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ecosystem-documentation#21]
Project should be configured in such way that .html extensions are not visible to the user (nice urls), all being listed as "folders".

Example https://ansible.readthedocs.io/projects/dev-tools/

Any existing incoming links can be redirected using something like https://github.com/ansible/ansible-lint/blob/main/docs/redirects.yml

**Comment by gotmax23** [comment]
https://github.com/ansible/ecosystem-documentation/blob/0e6002455526c5314e5d631cba160bd818e78a59/mkdocs.yml#L8

is the setting in question.

**Comment by samccann** [comment]
And explained here - https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

Is this something we should recommend for all mkdocs projects?

**Comment by oraNod** [comment]
I get why "nice" urls are preferred but `use_directory_urls: false` is in the configuration for the ecosystem template: https://github.com/ansible/ecosystem-documentation/blob/main/templates/ecosystem.html

Setting `use_directory_urls: true` (default) means we'd need to refactor the ecosystem page. This change would also mean adjusting redirects we set up for the execution environment urls in `ansible/docsite`: https://github.com/ansible/docsite/blob/36f46f2cd06f326521c6e4752265894d1eb9a787/.htaccess#L366
