### ISSUE TITLE
Playbook doesn't work when I use --execution-environment-image but works when I don't use the flag and I don't understand why

### ISSUE THREAD

**Issue by matheus-hatzlhoffer** [ansible/ecosystem-documentation#42]
Hello, I am trying to learn about ansible and I was following the instructions provided in the [documentation ](https://ansible.readthedocs.io/en/latest/getting_started_ee/run_execution_environment/#run-against-a-remote-target), but I am not understanding some behaviors.

I built the environment image with `ansible-builder build --tag postgresql_ee` and defined my hosts.yaml with a vm and a docker container IPs:

```sh
all:
  hosts:
    docker:
      ansible_host: 172.17.0.2
      http_port: 2222
    vm:
      ansible_host: 192.4.124.58
      http_port: 22
```

The playbook and image are equal as described in the documentation. But when I run `ansible-navigator run test_remote.yml -i inventory --execution-environment-image postgresql_ee:latest --mode stdout --pull-policy missing --enable-prompts -u root -k -K --ce docker` it doesn't work in the vm, but works with docker.
![image](https://github.com/ansible/ecosystem-documentation/assets/48157146/3ae4401c-9d90-4c3c-98af-fd2c2fcd854e)

The error is:
>```fatal: [vm]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "failed": true, "module_stderr": "Shared connection to 192.4.124.58 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127, "warnings": ["No python interpreters found for host vm (tried ['python3.12', 'python3.11', 'python3.10', 'python3.9', 'python3.8', 'python3.7', '/usr/bin/python3', 'python3'])"]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}```

I understand this error is about the missing python3 dependency in the vm. Makes sense, the vm hasn't python installed. However I don't understand why some commands work and this one doesn't .

if I run `ansible-navigator run test_remote.yaml -i inventory --mode stdout --enable-prompts -u root --ce docker` it works 
![image](https://github.com/ansible/ecosystem-documentation/assets/48157146/3126e434-d51b-4ae1-8e90-e82c65ea0d8d)

If I run `ansible-playbook -i inventory/hosts.yaml test_remote.yaml` it also works
![image](https://github.com/ansible/ecosystem-documentation/assets/48157146/32a442d4-7462-4046-97c4-5f4e228526dc)

What is the difference that I don't understand between running the ansible-playbook command, the ansible-navigator run command without the --execution-environment-image flag and the ansible-navigator run command with the --execution-environment-image flag?

Why does python need to be installed on the target node in the first command and in the other two it does not need to be installed in the other 2 commands?

----

**env:**

wsl2 with ubuntu 22.04
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```
```
ansible-playbook [core 2.16.6]
  config file = None
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user>/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<user>/.local/bin/ansible-playbook
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
```
ansible-navigator 24.3.2
```
```
ansible [core 2.16.6]
  config file = None
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user>/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<user>/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by oraNod** [comment]
Hi @matheus-hatzlhoffer Welcome and thanks for getting in touch. It's awesome that you're using execution environments and learning Ansible. However, since this is more of a general question rather than an issue with the documentation, may I suggest that you ask in the forum? A great place to ask your question is here: https://forum.ansible.com/c/help/6/none

You'll find lots of friendly and helpful people from the community in the forum. And you'll probably get a more detailed answer faster than you will by asking in an issue thread. We can also leave this issue open and see if the answer is something we should add to the documentation to help the next person who might encounter it.

**Comment by matheus-hatzlhoffer** [comment]
Hello @oraNod, thanks for the heads-up =). I created a [topic](https://forum.ansible.com/t/ansible-navigator-run-vs-ansible-playbook/5914) in the forum you sent
